blank_issues_enabled: true
contact_links:
  - name: ICSx⁵ Community Forum
    url: https://icsx5.bitfire.at/forums/
    about: Please use our forum for questions, support, suggestions, bug reports etc.

